site_name: Carbon Copycat Games
site_description: We like to make games.
site_author: carboncode
copyright: Copyright &copy; 2019-2020 <a href="https://carboncopycatgames.com/">Carbon Copycat Games</a>
nav:
    - Home: index.md
    - Victorious: victorious.md
#    - Bit Champs: bitchamps.md
    - Privacy Policy: privacypolicy.md
    - Contact: contact.md
theme:
    name: null
    custom_dir: 'theme'
    navigation_depth: 3
